### ISSUE TITLE
Media and AtomicImageCaching not in scope

### ISSUE THREAD

**Issue by anciltech** [Halle/AsyncFilmstripImage#1]
Hi Halle

Thanks for uploading the code for this tool! 

Am I missing an Import or something else? Media and AtomicImageCaching are not in scope
Sorry if it's a simple answer, I'm relatively new to programming ; ) 

<img width="1037" alt="Screenshot 2023-04-20 at 08 37 16" src="https://user-images.githubusercontent.com/79978026/233279709-0fc12fa5-6931-4113-ae12-669cc5349683.png">

**Comment by Halle** [comment]
Hey @anciltech ! Ha, I didn't notice that issues are on. I actually just put this on Github after a request to show this when it came up on an offline discussion, and unlike most things here it isn't actually a freestanding module. I will tighten up the description so that is clearer.

**Comment by anciltech** [comment]
Ah too bad, but thanks for clearing that up! I'll take inspiration from what I can see here ; )
